### ISSUE TITLE
Gyro input

### ISSUE THREAD

**Issue by peicou** [nathanhoad/godot_input_helper#24]
Hello,

Have you considering adding gyro input to the helper? I think it'd be useful as it seems like Godot's support for gyro is limited to mobile devices.
Having better support for gyro controllers would be really useful (PS5, Switch, etc). What are your thoughts about it?
Thank you for your great module!

**Comment by nathanhoad** [comment]
It looks like Godot has limited support for accelerometer stuff and I'm not entirely sure what Input Helper would even provide there.
