### ISSUE TITLE
Docs suggest running an example which is not included in the actual addon

### ISSUE THREAD

**Issue by regner** [nathanhoad/godot_input_helper#32]
**Describe the bug**

**Affected version**

- Input Helper version: 4.3.2
- Godot version: 4.2.1

**To Reproduce**

1. Install the addon via the Godot assetlib
2. Note that `res://addons/input_helper/device_tester/device_tester.tscn` is not avilable, but the docs suggest it should [here](res://addons/input_helper/device_tester/device_tester.tscn)

**Expected behavior**
To be able to find `res://addons/input_helper/device_tester/device_tester.tscn`

**Screenshots**
The plugin itself
![image](https://github.com/nathanhoad/godot_input_helper/assets/815037/ce00fc40-34ba-4e3c-a899-e57d0b264830)

Available resources
![image](https://github.com/nathanhoad/godot_input_helper/assets/815037/6c2c8a1b-4177-4e1e-b41b-0d2ac8c89fbb)

**Comment by nathanhoad** [comment]
I've updated the docs that referred to the device tester. If you want access to the examples folder you have to clone the full repository.

**Comment by regner** [comment]
Yeah that's wher I ended up getting it from. Thank you very much for your work on this plugin, and for fixing the docs so quickly. It's greatly appreciated. :) <3
