### ISSUE TITLE
replace_joypad_input_at_index exhibits unexpected behavior on switching from JOYPAD A

### ISSUE THREAD

**Issue by moraguma** [nathanhoad/godot_input_helper#36]
**Describe the bug**
On calling replace_joypad_input_at_index on an index not yet defined for an action that responds to JOYPAD A, will replace JOYPAD A with the new event instead of adding it to the correct index

**Affected version**

- Input Helper version: 4.3.3
- Godot version: 4.2.2

**To Reproduce**

1. Consider the case in which an action has the inputs [JOYPAD A] 
2. If we call replace_joypad_input_at_index with the action Y at the index 1, the replacing action will be set as JOYPAD A by default, and the final input list will be [JOYPAD Y]

**Expected behavior**
The input list associated with the action should be [JOYPAD A, JOYPAD Y]. Intead, Y replaced A

**Proposed solution**
This happens due to the following line @ replace_joypad_input_at_index. On creating a new InputEventJoypadButton, the button_index is [set to 0 by default](https://docs.godotengine.org/en/stable/classes/class_inputeventjoypadbutton.html#class-inputeventjoypadbutton-property-button-index), which is the key for the A button, instead of an invalid button, as it should be.

`var replacing_input = InputEventJoypadButton.new() if (inputs.is_empty() or inputs.size() <= index) `

This can be fixed by replacing this line with the following, which correctly defines the replacing_input as an invalid one

```
var replacing_input
if inputs.is_empty() or inputs.size() <= index:
  replacing_input = InputEventJoypadButton.new()
  replacing_input.button_index = JOY_BUTTON_INVALID
else:
  replacing_input = inputs[index]
```

**Comment by moraguma** [comment]
Hey, I hope that's fine. I opened a PR that implements this proposed solution #37

**Comment by nathanhoad** [comment]
Thanks 👍
