### ISSUE TITLE
Godot 4 version

### ISSUE THREAD

**Issue by SpyrexDE** [nathanhoad/godot_input_helper#7]
I really would like to use this plugin in my Godot 4 project. Will it get updated to that version any soon?

**Comment by nathanhoad** [comment]
Yep 👍 I'm in the process of migrating all of [my addons](https://github.com/nathanhoad?tab=repositories&q=godot&type=public&language=&sort=) to Godot 4.

**Comment by nathanhoad** [comment]
As of [v3.0.0](https://github.com/nathanhoad/godot_input_helper/releases/tag/v3.0.0) the addon is for Godot 4.
